language: java
services:
- docker
env:
  global:

  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - secure: gzf763SSQtaj2w/acMG1QCk9RPr+kgr2P37zbflR5WTbE1ZFlC8vKwtL9EDWyOQJbE40U3yI9/vaiN9kENW2sd+TgNbCEG6znRGOAEqCLUFi11USOjXUeL5HAaWKLRgYJI4uWErg3/fDP1u+ghmyCXWEb5+7xfk5UWOt/nCMDAY1FvSiBOnzLegNxyKirumHfP534OZTEtWS4F3MjMTvDgTInByVbXNiv6/w8uBkd3pDdUfKfnJmkQz+13vkWN/AW7yi94FAR0lBdTj1JALPMef12eE3gez7dfqx/D/fJkqLDJEFW5ehtQeSg35Z9pC9jR85vKfmn/SqSotZ+TsXPokFtTWgQsORBz1A2baRdGA1zC5zAS22qap1AAA1aeyriUXRg6d0BM11uSsUWYOuYqUvKM9W++/PMKKTw8jZksVpYiBdH6KPXVJ2FYpAZPsnjijKEN0yuEO6MMb9gTQD00U3agSZA1CyEkSaYON5MR40BBFBVwETMhVcMbOKePuO+JFBl60sj/FXhqZI/VRCP/wE0O5JLSjl7vGUUC/HDQ++ePJOPoVKKpW7QTMF9bT4V8CRhSpMLfn3yymgZmEUJ83pm5kj7DFlhal2WgHLqCPTnBRZy8R7O2+IYF1i2ASU8gyQ2YXdWPQy3jQObL/viVdonb4A2Eefp7ylUEmUEOo=
  - secure: qw6pNKA9zWg4ic+H6cWoa5Pa0nPTx5VBcCe56ERMXl7iWIqKuFd8/Hc+ttvncwvy6SK5P5INj4jwf4yJq6TbQUTGjY/h7ghtCY6pf3NdNKjgJ65A7Oc+5owidCYa87dfB6z/BJXgEAdSImrY0TZ5N9L09m8BZQZHnLf2QJZBkfG8pLbbDvnUlHd/+yccIlWEJ95p4F6RSh6MLnJMA5DGmbq4Cxais1AauLAu9UC1BekDG1ZlLwBKFKXVqakLmOX9OXA2U3F+ebSQf0BhBioM2uJVep8e87RyvQWU8A0MU6Ov7kzXua+mgBGzAyX3OU5zcfkBao/9PvuWWVTcTMaBdt8oz1QC+0e7593ZLT9AvSZzWmB9pAnHbB7ju/l8kvz9gNo/T9gK6v5wOxTuTkgqIwIq/U7amWR4nuwGrgq8li6P49cOan1IOkyPD+HJFxExmvmndkP3XQQwBesPdPNwg3hNsLJ7sCtB+p15VrsyZg/0EIv6J4cR9JlXIFsCubo5Z5cs9TX5Y+VaT59FFZsVxpbw64+RECJ1/mHrP90joHyDMvIkdT4M/alrBasrbtVhpyM3ujqH+urz11E4urwh3sSfAD3s6W1leJRW/wKjmHtgeGJoSRlhtsHtXSgstnsydEm4XrDB/9VEfqT9yucRITcYKwQ2wKrZaMAQC9zpdNw=
before_install:
- openssl aes-256-cbc -K $encrypted_81b902ed6543_key -iv $encrypted_81b902ed6543_iv
  -in eksamen-devops-f7bc3c2f300a-kopi.json.enc -out eksamen-devops-f7bc3c2f300a-kopi.json
  -d
- curl https://sdk.cloud.google.com | bash > /dev/null
- source "$HOME/google-cloud-sdk/path.bash.inc"
- gcloud auth activate-service-account --key-file=eksamen-devops-f7bc3c2f300a-kopi.json
- gcloud auth configure-docker
- gcloud config set project "${GCP_PROJECT_ID}"
install: true
script:
- |-
  set -ex;
  docker build -t "${IMAGE}:${TRAVIS_COMMIT}" . && \
  docker push "${IMAGE}:${TRAVIS_COMMIT}" && \
  set +x
